version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
    labels:
      - "java"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:30"
    labels:
      - "github-actions"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20
