version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
    labels:
      - "java"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20
    groups:
      gradle-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      gradle-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:30"
    labels:
      - "github-actions"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20
    groups:
      github-actions-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
