name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: dependencies, gradle
          pr-title-template: 'chore: Bump Gradle Wrapper from %sourceVersion% to %targetVersion%'
